
{{- if .Values.enabled }}
apiVersion: {{ include "silta-cluster.ingress-api-version" . | trim }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-deployment-remover
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if .Values.ssl.enabled }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http"
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
  - secretName: {{ .Release.Name }}-tls-deployment-remover
  {{- end }}
  rules:
  - host: webhooks.{{ .Values.clusterDomain }}
    http:
      paths:
      - path: /
        {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Release.Name }}-deployment-remover
            port: 
              number: 80
          {{- else }}
          serviceName: {{ .Release.Name }}-deployment-remover
          servicePort: 80
          {{- end }}
---
{{- if .Values.ssl.enabled }}
{{- if has .Values.ssl.issuer (list "letsencrypt" "letsencrypt-staging") }}
apiVersion: {{ include "silta-cluster.cert-manager-api-version" . | trim }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt-deployment-remover
spec:
  secretName: {{ .Release.Name }}-tls-deployment-remover
  dnsNames:
  - webhooks.{{ .Values.clusterDomain }}
  issuerRef:
    name: {{ .Values.ssl.issuer }}
    kind: ClusterIssuer
{{- if not ( .Capabilities.APIVersions.Has "cert-manager.io/v1" ) }}
  acme:
    config:
      - http01:
          ingress: {{ .Release.Name }}-deployment-remover
        domains:
          - webhooks.{{ .Values.clusterDomain }}
{{- end }}
---
{{- else if eq .Values.ssl.issuer "selfsigned" }}
apiVersion: {{ include "silta-cluster.cert-manager-api-version" . | trim  }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt-deployment-remover
spec:
  secretName: {{ .Release.Name }}-tls-deployment-remover
  duration: 2160h
  renewBefore: 150h 
  commonName: webhooks.{{ .Values.clusterDomain }}
  dnsNames:
  - webhooks.{{ .Values.clusterDomain }}
  issuerRef:
    name: {{ .Values.ssl.issuer }}
    kind: ClusterIssuer
---
{{- else if eq .Values.ssl.issuer "custom" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-deployment-remover
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ssl.crt | b64enc }}
  tls.key: {{ .Values.ssl.key | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}